name: release
on:
  release:
    types:
      - created

jobs:
  download_test_data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          python-version: 3.7
          activate-environment: test
          environment-file: .github/test_conda_env.yml
          condarc-file: .github/test_condarc.yml

      - name: install obsplus
        shell: bash -l {0}
        run: |
          pip install -e .[dev]

      - name: build docs
        run: |
          python scripts/stage_docs.py

      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
